using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace Pokemon_3080
{
    /// <summary>
    /// Interaction logic for Capture.xaml
    /// </summary>
    public partial class Capture : Window
    {
        private System.Windows.Threading.DispatcherTimer Timer = new System.Windows.Threading.DispatcherTimer();
        private int timer = 7; // The time availble for typing game
        private string newPokemon;
        private string result = "No";
        private List<string> PokemonNameList;
        private List<BitmapImage> PokemonImageList;
        private Random rnd;
        private int RndNumber;

        public Capture() // Capture, based in typing game
        {
            InitializeComponent();
            long tick = DateTime.Now.Ticks;
            rnd = new Random((int)(tick & 0xffffffffL) | (int)(tick >> 32)); // Use system time to initialize the random object
            PokemonNameList = new List<string>();
            PokemonImageList = new List<BitmapImage>();
            LoadPokemonName();
  
            RndNumber = rnd.Next(0,5);
            newPokemon = PokemonNameList[RndNumber]; // The pokemon is generated by the randomly choice of PokemonNameList
            LoadImage();
            ShowImage();
            AskingMessage.Text = "A Pixelmon appears in front of you.\nDo you want to capture it?";
            Timer.Tick += Timer_Tick;
            Timer.Interval = TimeSpan.FromSeconds(1);
        }


        public void LoadImage() // Load image of the shown pokemon
        {
            for (int i = 0; i <= 4; i++)
            {
                string filename = "/PokemonImage/" + i.ToString() + ".bmp";
                BitmapImage bmImg = new BitmapImage(new Uri(filename, UriKind.Relative));
                PokemonImageList.Add(bmImg);
            }
        }

        public void ShowImage() // Show the image of the pokemon
        {
            Image newImage = new Image();
            newImage.Source = PokemonImageList[RndNumber];
            newImage.Height = 175;
            newImage.Width = 175;
            Canvas.SetLeft(newImage, 0);
            Canvas.SetTop(newImage, 0);
            canvas.Children.Add(newImage);
        }

        public void LoadPokemonName() 
        {
            PokemonNameList.Add("Bulbasaur");
            PokemonNameList.Add("Charmander");
            PokemonNameList.Add("Squirtle");
            PokemonNameList.Add("Psyduck");
            PokemonNameList.Add("Caterpie");
        }

        public void Timer_Tick(object sender, EventArgs e) // Timer for typing game
        {
            timer--;
            count.Text = timer.ToString() + "s";
            if (typingbox.Text != pokemonname.Text && timer == 0)
            {
                Timer.Stop();
                MessageBox.Show("Such a shame that " + newPokemon +  " has run away!"); // If time exhausts and you haven't type in the full name of the pokemon, the pokemon will run away
                this.Close();
            }
        }

        public string Result
        {
            get { return result; }
        }

        public string NewName
        { 
            get { return newPokemon; }
        }

        private void YesButton_Click(object sender, RoutedEventArgs e) // The content of the word to be typed in will only be displayed after choosing yes.
        {
            Timer.Start();
            AskingMessage.Text = String.Empty;
            AskingMessage.Text = "Type in the following name: ";
            pokemonname.Text = newPokemon;
            timecount.Text = "Time Left:";
        }

        private void NoButton_Click(object sender, RoutedEventArgs e)
        {
            result = "No";
            this.Close();
        }

        private void typingbox_TextChanged(object sender, TextChangedEventArgs e) // Decide whether the input text is right
        {
            if (typingbox.Text == pokemonname.Text && timer != 0)
            {
                Timer.Stop();
                result = "Yes";
                MessageBox.Show("Congratulations! You get " + newPokemon + "！\nExtra 30 stardust and 3 eggs has been added to your pokect!" );
                this.Close();
            }
        }
    }
}
